import Head from "next/head"
import groups from "../modules/groups"
import GroupsList from "../components/GroupsList"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Schedule</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-xs lg:max-w-lg sm:max-w-md m-auto">
        <div className="flex sm:gap-36 gap-5 m-auto w-100">
          <GroupsList year={"I курс"} groups={groups[0]} />
          <GroupsList year={"II курс"} groups={groups[1]} />
        </div>
      </div>
    </div>
  )
}
