import Head from "next/head"
import groups from "../modules/groups"
import GroupsList from "../components/GroupsList"

export default function Home() {
  const years = ["I курс", "II курс", "II курс дист.", "III курс"]
  return (
    <div>
      <Head>
        <title>Schedule</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-xs lg:max-w-[80%] sm:max-w-md m-auto">
        <div className="grid grid-cols-2 lg:grid-cols-4 items-end lg:items-stretch gap-4 m-auto w-100 my-10">
          {years.map((year, key) => {
            return (
              <GroupsList year={year} yearIndex={key} groups={groups[key]} />
            )
          })}
        </div>
      </div>
    </div>
  )
}
